services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: racha-pjb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
